---
- name: cicd with docker module
  hosts: ansible_host
  tasks:
  - name: Remove image
    docker_image:
      state: absent
      name: pjs8590/my-hello-world
      tag: latest
#  - name: Log into DockerHub
#    docker_login:
#      username: docker
#      password: rekcod
  - name: Build an image
    docker_image:
      build:
        path: ~/hello-world
      name: pjs8590/my-hello-world
      tag: latest
      push: yes
      source: build
